name: eid_wallet
description: National EID Mobile ID Wallet — OpenID4VCI issuance and OpenID4VP presentation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: NotoSerifMyanmar
      fonts:
        - asset: assets/fonts/NotoSerifMyanmar-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerifMyanmar-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerifMyanmar-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerifMyanmar-Bold.ttf
          weight: 700
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Variable.ttf
